### PR TITLE
Fixed the broken links on overview page

### PR DESCRIPTION
**Pull request by chenrui333**
Looks like the three links on the overview page are broken, here is the fix.

### CODE REVIEW

**Comment by ark3** [comment]
Thanks for the PR! The type of fix proposed by @vemv in #817, i.e. adding a leading slash, seems more correct to me.

**Comment by chenrui333** [comment]
interesting, I thought about the relative link references. but i found the other locations on the same page are actually doing the direct link references. I will make another update to see if it fits.

**Comment by chenrui333** [comment]
@ark3 yeah, indeed that is much better, I also correct the other locations. Please review again.

**Comment by chenrui333** [comment]
@ark3 can you give another look? Thanks!

**Pull request merged**
