### PR TITLE
search "Application Support" folder

### PR DESCRIPTION
**Pull request by njayp**
Signed-off-by: njayp <nickjaypowell@gmail.com>

## Description

The telepresence config file can be in either "\~/Library/ApplicationSupport" or "\~/Library/Application Support", so check both places

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to either submit a docs PR, or tell Matt about the necessary documentation changes.
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.

### CODE REVIEW

**Comment by thallgren** [comment]
AFAICT, telepresence will never use the variant without a space. The `UserConfigDir()` function hardcodes the darwin folder to `home + "/Library/Application Support"`.  The same is true for `os.UserConfigDir()`.

@njayp when are you seeing the variant without a space?

**Comment by thallgren** [comment]
@njayp can you please provide more info here or close the ticket?

**Comment by njayp** [comment]
> @njayp can you please provide more info here or close the ticket?

sorry, I missed your first comment. It seems like the script currently has "~/Library/ApplicationSupport", without the space in line 171, so I changed it to have the space. At the same time, the script seems to work "as is" for everyone else, so I added logic to allow both locations

**Comment by thallgren** [comment]
Ok, in that case I suggest that you simply change it to "~/Library/Application Support". If something, or someone, uses the name without space, then there's an error somewhere else that we don't want to hide.

**Pull request merged**
