### PR TITLE
OSS 2.11 release note

### PR DESCRIPTION
**Pull request by josecv**
## Description

A few sentences describing the overall goals of the pull request's commits.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

**Review by knlambert — APPROVED** [review]

**Comment by knlambert** [comment]
Add something about the new archs

**Comment by anafilipadealmeida** [comment]
This is the [arm64 issue](https://github.com/telepresenceio/telepresence/issues/2786) solved that should be included in the release notes.

it would be cool to also mention Jeff’s [PR](https://github.com/telepresenceio/telepresence/pull/2992) in the "Feature: IPv6 support", since this was solved by a community folk!

**Comment by shepz** [comment]
> This is the [arm64 issue](https://github.com/telepresenceio/telepresence/issues/2786) solved that should be included in the release notes.
> 
> it would be cool to also mention Jeff’s [PR](https://github.com/telepresenceio/telepresence/pull/2992) in the "Feature: IPv6 support", since this was solved by a community folk!

I added something for arm64. For IPV6, it's already included : https://github.com/telepresenceio/telepresence/blob/josecv/rel-2.11.0/CHANGELOG.md?plain=1#L19

**Review by knlambert — APPROVED** [review]

**Comment by shepz** [comment]
> This is the [arm64 issue](https://github.com/telepresenceio/telepresence/issues/2786) solved that should be included in the release notes.
> 
> it would be cool to also mention Jeff’s [PR](https://github.com/telepresenceio/telepresence/pull/2992) in the "Feature: IPv6 support", since this was solved by a community folk!

@anafilipadealmeida done

**Review by knlambert — APPROVED** [review]

**Pull request merged**
