### PR TITLE
New community page in docs

### PR DESCRIPTION
**Pull request by hcavalieri**
This adds a new page to the docs website (telepresence.io/community) with helpful links for people looking to engage with the Telepresence community.

This is still a work in progress, I'll update this PR when this status changes 😉 

**Update 06.26 2:47PM:** I'm currently stuck on how to fix line 95 of `docs/build-website.py`. I don't have access to the Netlify dashboard and couldn't get Python running locally, so my guess is that this line breaks the deploy as it tries to `write_text` to an unexisting file. If someone with Python experience could debug this, that'd be great!

**Update 06.29:** This PR is now ready for merging 🎉

### CODE REVIEW

**Comment by ark3** [comment]
What are you trying to do with your Python code?

Can you make this new page work like `about.html` if it will always remain just one page? Or like `case-studies` if it's intended to be multiple pages? Neither of those requires any Python magic.

**Comment by hcavalieri** [comment]
I'm just trying to copy `community.html` into `_book/community/index.html` after gitbook is done, but if there's a simpler way I'm all in for it! How's `about.html` being rendered to the website?

**Comment by ark3** [comment]
The existing doc build stuff takes care of that automatically; files and directories are copied over for you.

I recommend you Just remove your Python change and examine the result you get by using the existing machinery.

**Comment by hcavalieri** [comment]
Well, I never knew it was that simple 😅 

[The preview](https://deploy-preview-1390--telepresence.netlify.app/community) is looking perfect, I'm just waiting on @kelseyevans to review it before we can merge it. Thanks for the time and patience Abhay!

**Comment by kelseyevans** [comment]
LGTM @ark3 could you please merge this?

**Pull request merged**
