### PR TITLE
Add brew support for tel2oss version builds

### LINKED ISSUE #3609: Provide Homebrew release of OSS version "tel2oss" of Telepresence
I have implemented a sample Homebrew formula for the "tel2oss" here: https://github.com/tonur/homebrew-telepresence-oss

**Please describe your use case / problem.**
Installing from a binary download link is not preferred, as the [Telepresence install page](https://www.getambassador.io/docs/telepresence/latest/install?os=macos) for the standard release also suggests installation via brew.
My use case would be much improved if I could install the "tel2oss" version of Telepresence with such a command:
`brew install datawire/blackbird/telepresence-oss`

**Describe the solution you'd like**
Add the "tel2oss" as a separate Homebrew formula as part of the [release build](https://github.com/telepresenceio/telepresence/blob/52b5ce0103371b49da26ebc1a68c554e3955e52f/build-aux/main.mk#L336) which currently uses [packaging/homebrew-package.sh](https://github.com/telepresenceio/telepresence/blob/release/v2/packaging/homebrew-package.sh) to only release the "tel2" standard version.

The best solution would be to host this Homebrew formula on a Datawire controlled repository, likely the current Homebrew tap location for this: https://github.com/datawire/homebrew-blackbird as a formula called "telepresence-oss".
As mentioned, this formula for the "tel2oss" can perhaps serve as inspiration: https://github.com/tonur/homebrew-telepresence-oss.
This requires changes to the [packaging/homebrew-package.sh](https://github.com/telepresenceio/telepresence/blob/release/v2/packaging/homebrew-package.sh) file to automate new releases.

**Describe alternatives you've considered**
Hosting the formula myself, but this is undesirable for other users, as a random Github users private repository is less trusted than the official Datawire controlled repository.

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions)
```
> telepresence version
OSS Client     : v2.18.0
OSS Root Daemon: v2.18.0
OSS User Daemon: v2.18.0
Traffic Manager: v2.17.0
Traffic Agent  : not currently available
```
  - Kubernetes Environment and Version
  AKS Version 1.28

**Additional context**
This applies only to MacBook and perhaps Linux, as these are the only users of Homebrew.

### PR DESCRIPTION
**Pull request by tonur**
## Description

Added support for installing the Open Source version of Telepresence (tel2oss) via a Homebrew formula originally created here: https://github.com/tonur/homebrew-telepresence-oss.
Closes #3609 

## Checklist
Regarding the checklist, I am not sure that this change constitutes an update to the CHANGELOG.yml or any release notes.
I would be happy if the maintainers would comment on this to see if this is necessary.

 - [x] I made sure to update `./CHANGELOG.yml`.
 - [x] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [x] I updated `CONTRIBUTING.md` with any special dev tricks I had to use to work on this code efficiently.
 - [x] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [x] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.
 
 Waiting to check the last item until I get feedback on the first two items on the checklist.

### CODE REVIEW

**Review by thallgren — APPROVED** [review]

**Comment by thallgren** [comment]
This looks good to me. And yes, I think it would be great if you could add an entry to the changelog.

**Comment by tonur** [comment]
After this PR, a change could then be made to [telepresenceio/telepresence.io/docs/latest/quick-start/index.md](https://github.com/telepresenceio/telepresence.io/blob/45aeeeb6287e874c46bf00bad97f179abc83525e/docs/latest/quick-start/index.md?plain=1#L31), to be like the [telepresenceio/telepresence.io/docs/pre-release/install/index.md](https://github.com/telepresenceio/telepresence.io/blob/master/docs/pre-release/install/index.md?plain=1#L10):
```
# Install via brew:
brew install datawire/blackbird/telepresence-oss
```

**Comment by tonur** [comment]
I am so sorry about the amount of noise in this PR, I had some issues with syncing with the origin, due to me trying to do a `git merge release/v2 && git commit --signoff`, so I ended up doing a rebase instead. Apologies!
I would appreciate a quick re-review to ensure that everything is still in order, to your standards.

**Review by thallgren — APPROVED** [review]

**Comment by thallgren** [comment]
@tonur there's one more thing that needs to happen. The version of the `tel2` and `tel2oss` are not aligned, so the makefile must have two explicit targets. We won't publish both at the same time.

**Comment by tonur** [comment]
I am looking into modifying the makefile to have two targets today, will request a review again when this is done.
Thanks for letting me contribute!

**Comment by tonur** [comment]
I must admit, I am not totally clear how the "tel2" package is built. Is it built from this repository? 

I assume that by introducing two targets, I have to modify the UserClient name to be "OSS Client" when building `tel2oss` and "Client" when building `tel2`, but I have difficulties finding out where to modify this name. It seems to come from the UserClient name found in the getConnectorVersion method here: https://github.com/telepresenceio/telepresence/blob/release/v2/pkg/client/cli/connect/connector.go#L336
Is this correct? Can you perhaps point me in the right direction on how to proceed @thallgren? 
Especially how to compile the non oss `tel2` version, since I have issues building other versions than the `tel2oss` version by running `make build` that builds the "./build-output/bin/telepresence" file.

**Comment by thallgren** [comment]
The name you point to is the name of the connection. The name that the binary reports as "OSS Client" is set here:

https://github.com/telepresenceio/telepresence/blob/release/v2/pkg/client/cli/main.go#L45

and it is set differently when building the enterprise version of Telepresence. I don't think it's relevant to this PR at all.

That said, and sorry for the confusion earlier, I think you need one target for the `tel2oss` only. The `tel2` package is currently built by calling the from the enterprise Makefile like so:
```
    packaging/homebrew-package.sh $(patsubst v%,%,$(TELEPRESENCE_VERSION)) $(GOARCH)
```
and we'll need to change the last argument there to `tel2` instead of `$(GOARCH)` while you keep the `tel2oss` here.

**Comment by tonur** [comment]
Hey again @thallgren. Apologies for the delay, I have been occupied with a job change.
I removed the tel2 target, so I think everything is good on my end if this PR only requires a change in the enterprise Makefile (Which I don't know where where it is located. I assume it is elsewhere, non public).
Otherwise, if I need to make other changes, please let me know.

**Comment by thallgren** [comment]
Hey @P0lip , Just a heads up. I intend to merge this shortly, and it will require a small change in the enterprise code when you decide to include it. See [this comment](/telepresenceio/telepresence/pull/3626#issuecomment-2200150895).

**Pull request merged**
