### PR TITLE
Share CIDR routing to container method

### PR DESCRIPTION
**Pull request by isra17**
This workaround an issue in sshuttle on some host (See: https://github.com/telepresenceio/telepresence/issues/1220).

- A bit of refactoring was done to share the CIDR code between VPN and Container outbounds. 
- I also added a faster, more reliable way to get the serviceCIDR from the kube-apiserver command line parameters.
- I also added a filter on guessed pods CIDR to avoid collapsing into public network. While testing my PR, I had a cluster with pods in both `172.x.x.x` and `192.x.x.x` which end up collapsing in `128.0.0.0/1`

### CODE REVIEW

**Comment by ark3** [comment]
Not stale! I’ll get to this next week.

**Comment by ark3** [comment]
Your CIDR refactor is great! I wish you had posted that as a separate PR, or at least a separate commit. I would cherry-pick that onto master immediately; it's a pure win.

The core of this PR basically reverts #858 and makes the container method uses more likely to need things like `--also-proxy`. I'm flabbergasted that this solved #1220 for you, but I admit I _really_ don't understand that issue yet, and I'm frustrated that I have no way to replicate it myself.

**Comment by isra17** [comment]
My theory is that #1220 is caused by the sshuttle component and a mix of the cloud and host environment... Luckily I was able to reproduce on my macbook, but not on my Desktop. I wasn't able to find the root cause, but it's probably one of those bugs that goes down to the network packet. that said, I can understand why the current behavior would be wanted. What do you think of (yet another) parameters like `--proxy-cidr` that would allow overriding `0.0.0.0`?

Otherwise I can work on splitting the PR along with #1373. I'm a bit busy right now, so maybe this will come in the next weeks.

**Comment by ptemmer** [comment]
As to not revert #858. What about a parameter like `--never-proxy` or what have you, to exclude certain ips or domains to go through sshuttle, opposite to `--also-proxy`

**Comment by isra17** [comment]
My issue with `--never-proxy` is that it isn't really the case, you still want to proxy the cluster cidrs to the remote cluster.

**Comment by ptemmer** [comment]
Yes, that seems valid to me, it's just a different approach to the problem. While `--never-proxy amazonaws.con` would proxy everything, except the domain name specified, `--no-global-proxy` would only proxy the service CIDR and require you to explicitly specify any others. In my case, where I only have problems with amazonaws.com, it seems easier to just exclude that domain from being proxied, and leave all the rest as it is.

**Comment by ark3** [comment]
This PR is stale now. The CIDR logic refactor (#1420) has landed and there is a separate PR (#1456) that addresses the original goal here. Closing this in favor of the other PR. Thank you!

**Comment by aviau** [comment]
There are still lines of code in this PR that are needed in master! I'll open a new PR.

**Pull request closed without merging**
