### PR TITLE
Detect  cluster domain and build FQDN for hostnames involved in connectivity tests

### PR DESCRIPTION
**Pull request by ipleten**
My attempt to address #1307.

### CODE REVIEW

**Comment by ark3** [comment]
Can you help me understand the goal for this change?

You've set ndot=1 in your Pod, presumably for a good reason. Otherwise you could fix your problem by not modifying ndots in your Pod. Is that fair?

So I think the correct solution would be for Telepresence not to misbehave when ndots is set, presumably by doing fully-qualified lookups only. Does that make sense?

Or do you _really_ want networking to behave differently in the cluster and locally?

**Comment by ipleten** [comment]
We changed settings to `ndots:1` as default value `5` dramatically increases latency for our services. (https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html)
We can't change it to default without impacting performance. We plan to use Telepresence for TEST cluster and probably for PROD for deeper debugging.  While TEST cluster might work fine with "ndots:5" that requires us to use a different configurations for TEST/PROD clusters.
Currently it's impossible due to issue #1307.
So for now workflow looks like: 
1) Edit deployment and set ndots
2) Wait till pod got recreated :(
3) Swap deployment and do some debugging developing
4) Revert everything back.

**Comment by ipleten** [comment]
I tried to figure out how to get an  k8s 'cluster-domain' value and seems there is no reliable (via API) way to do that.

**Comment by ipleten** [comment]
The funny thing, while python works and is able to resolve, problem seems come from `torsocks`:

python:
> root@python-test-ndots-ipleten-5bdbb59c74-zjwdv:/# python3 -c "import socket; socket.socket().connect(('kubernetes.default', 443))"

>root@python-test-ndots-ipleten-5bdbb59c74-zjwdv:/# torsocks python3 -c "import socket; socket.socket().connect(('kubernetes.default', 443))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -4] Non-recoverable failure in name resolution

curl:
>root@python-test-ndots-ipleten-5bdbb59c74-zjwdv:/# curl google.com -s >/dev/null
root@python-test-ndots-ipleten-5bdbb59c74-zjwdv:/# torsocks curl google.com
curl: (6) Could not resolve host: google.com

As well as I could confirm that proxy is working .
>root@python-test-ndots-ipleten-5bdbb59c74-zjwdv:/# torsocks curl http://192.168.0.1 -s > /dev/null

I have ndots:1 on this pod and create ssh SOCKS5 proxy to another machine on localhost:9050.


I tried to call socket.getaddinfo and getfqdn() but none of them works via `torsocks`.

**Comment by ark3** [comment]
I'm missing some context here (or I have forgotten... sorry!). The ssh-based socks proxy doesn't support the TOR extensions for DNS, does it? And why is torsocks relevant here, anyhow?

You can construct FQDNs by reading `/etc/resolv.conf` in the proxy pod. We already pass that file back to the CLI application via podinfo.py, and parse that file in container.py, but we don't use it for this purpose. Yes, this is not a reliable or supported mechanism, but that is the unfortunate truth of working on Telepresence.

**Comment by ipleten** [comment]
Yeah `torsocks` doesn't work with ssh proxy :(
I tried to figure out the whole chain and reproduce it without telepresence, my bad. 
Sorry for noise. I'll try to concentrate on FQDN.

**Comment by ark3** [comment]
Ah, okay. I'm sorry you had to figure out/reverse engineer the chain. We need to have far better documentation!

Thank you very much for your help on this.

**Comment by ark3** [comment]
Not stale. I'd like to poke at fixing the FQDN stuff everywhere in Tel. And maybe @ipleten can get us most of the way there! :smile:

**Comment by ipleten** [comment]
Sorry, I'll try to find time to fix that.

**Comment by ipleten** [comment]
Should I fix formating?

**Comment by ipleten** [comment]
hm... it also hardcoded for 'container' mode

**Comment by ipleten** [comment]
Not sure that I need to do with failed test.
I tested it a bit manually and it works on my cluster now.

**Comment by ipleten** [comment]
Hello, @ark3 
Could you please review, if you have a moment, and let me know if it looks more or less fine?

**Comment by ark3** [comment]
Sorry I haven't had a chance to work on this. At a glance, this looks excellent! But I need to try it out on a few machines and clusters before I land it, and that will have to wait for next week. 

MacOS CI failing is its own problem (#1455)...

Thank you for this great stuff!

**Comment by ipleten** [comment]
not stale.

**Comment by ark3** [comment]
I'm concerned about `get_cluster_domain(...)` itself. It has no error checking and it can potentially return a bogus answer. There's no fallback path to the current behavior. Aside from that function, the rest looks good. Thoughts?

**Comment by ipleten** [comment]
> I'm concerned about `get_cluster_domain(...)` itself. It has no error checking and it can potentially return a bogus answer. There's no fallback path to the current behavior. Aside from that function, the rest looks good. Thoughts?

Well, while it's possible to fallback to current behavior, I'm not sure how to detect that cluster domain was detected properly. Looks like yet another `try`  https://github.com/telepresenceio/telepresence/blob/b9661e48c05a41dd457273dce5014d73ef315ec7/telepresence/outbound/local.py#L66  is needed, hence if it fails for new logic we could try current 'kubernetes.default' hostname?

**Pull request closed without merging**
