### PR TITLE
feat: add imagePullSecrets to hooks

### PR DESCRIPTION
**Pull request by jef**
## Description

The current Helm chart doesn't include `imagePullSecrets` to `hooks.busybox` `hooks.curl`. This PR adds that implementation and documentation around the `hooks` key.

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [x] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

**Review by thallgren — CHANGES_REQUESTED** [review]
Thanks for contributing this. Please also add a description to the PR.

**Comment by jef** [comment]
Added! Thanks @thallgren.

**Review by thallgren — APPROVED** [review]

**Comment by thallgren** [comment]
Something isn't right with this PR. The integration test fails with:
```
telepresence helm install: error: failed to install traffic manager: template: telepresence/templates/tests/test-connection.yaml:12:17: executing "telepresence/templates/tests/test-connection.yaml" at <.image.hooks.busybox.imagePullSecrets>: nil pointer evaluating interface ***.hooks, exit code 1
```

**Comment by jef** [comment]
@thallgren, I totally did a typo 😆 This should work now...

**Comment by thallgren** [comment]
Thanks for your contribution @jef.

**Pull request merged**
