### PR TITLE
Add a make rule for building the helm chart

### PR DESCRIPTION
**Pull request by ghost**
## Description

New make rule `make build-chart` that will be used by the Telepresence pro system tests

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [x] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

**Review by thallgren — COMMENTED** [review]
Why is this needed? I'm asking because I'm about to move the `packaging/*chart*` files to telepresence-pro, where the chart will also include the ambassador-agent. The act of publishing a chart that isn't embedded in the `telepresence` binary will be performed there.

I'm also contemplating a `telepresence helm pull` command that would extract the embedded chart from the binary. Would that help your use case?

**Comment by ghost** [comment]
> Why is this needed? I'm asking because I'm about to move the `packaging/*chart*` files to telepresence-pro, where the chart will also include the ambassador-agent. The act of publishing a chart that isn't embedded in the `telepresence` binary will be performed there.
> 
> I'm also contemplating a `telepresence helm pull` command that would extract the embedded chart from the binary. Would that help your use case?

@thallgren I didn't want to duplicate code in the Telepresence Pro repo and instead use this make target to generate the chart and pass it to the system tests.

If you want to move these scripts to the Telepresence Pro repo I can rebase that once it's ready.
Or I can also use the helm pull command.

Let me know how do you want to proceed, and I can update the TP Pro PR.

Would you be able to do this tomorrow? If not, I can temporarily call `packaging/build_chart.sh` from the Pro repo and once you're done the system tests can be updated.

**Comment by thallgren** [comment]
@aosoriodw do we still need this?

**Comment by thallgren** [comment]
Ping @aosoriodw

**Pull request closed without merging**
