### PR TITLE
Add Helm chart setting to disable personal intercepts.

### PR DESCRIPTION
**Pull request by MaxMuzh**
Signed-off-by: Max Muzh <mmuzh@augury.com>

## Description

Adds a new intercept structure to the Helm chart with one single `disablePersonal` boolean setting which defaults to false. When set to true, the traffic-manager will respond with an error if an attempt is made to create an intercept that doesn't use the `tcp` mechanism.

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

**Comment by thallgren** [comment]
Thanks for providing this, but I'm afraid this feature was already released in Telepresence 2.8.3. See Helm chart setting `intercept.disableGlobal`.

**Comment by thallgren** [comment]
@MaxMuzh Can you please provide a motivation in the commit comment explaining why this is needed?

**Comment by MaxMuzh** [comment]
Hi @thallgren,
Thank you for your reply.
In our company we use only Global intercepts because our system doesn't entirely supports passing of http headers.
In addition, as users of the open source version of telepresence we sometime violate by mistake your EULA by using too many personal intercepts (which doesn't work for us as explained above)

**Comment by thallgren** [comment]
@MaxMuzh You can already accomplish what you want by passing the following values to the Helm chart:
```yaml
agent:
  image:
    name: tel2
    tag: 2.8.5
```
This will cause the traffic manager to always inject the OSS agent. It's not capable of doing http intercepts and will not accept the http flags.

**Comment by thallgren** [comment]
I'm closing this for two reasons:
1. Another solution for the problem already exists.
2. Similar to the traffic-agent, the telepresence client will be also available in two shapes in the near future. One pure OSS that doesn't accept --http options, and one enhanced "pro" version that does.

**Comment by GuyCarmy** [comment]
Hi @thallgren, is there already a pure OSS client like described here?

**Pull request closed without merging**
