### PR TITLE
fix: Add deploymentconfig support to --deployment

### LINKED ISSUE #1037: Client can not find a pre prepared DeploymentConfig using the --deployment flag
A 3. party actor could prepare a proxy using a DeploymentConfig on Openshift as the deployment strategy. 

This scenario is currently not covered by the --deployment handling as it assumes only Deployments can exist and will never attempt to look for a DeploymentConfig.

### PR DESCRIPTION
**Pull request by aslakknutsen**
Fixes #1037

### CODE REVIEW

**Comment by ark3** [comment]
Thanks for the PR! I'll try to take a look at this soon.

**Comment by aslakknutsen** [comment]
@ark3 Forgot to ask; Do you want me to open an issue to describe the change and add a news fragment?

**Comment by bartoszmajsak** [comment]
@ark3 No pressure, just curiosity - is there anything holding back this PR from being merged?

**Comment by ark3** [comment]
Sorry, been busy with other work. I did a bit of reformatting to get the linters to pass, and then some refactoring to make the control flow a little easier. I don't _think_ I broke anything, but can you please verify that this branch still does what you wanted? Thanks.

**Comment by aslakknutsen** [comment]
@ark3 Looks good from my testing. Thank you.

**Comment by ark3** [comment]
Great! Sorry, could you add an issue and a news fragment? I meant to ask for that sooner, but it completely slipped my mind!

**Comment by aslakknutsen** [comment]
@ark3 Done. I think :)

**Comment by bartoszmajsak** [comment]
A little bit late to the party but I tested it on my side and seems to work just fine!

**Pull request merged**
