### PR TITLE
Fix/docker deployment

### PR DESCRIPTION
**Pull request by netag**
- Adding ssl certs to k8s dockerfile
- Swapped deployment: explicitly add docker command to run

### CODE REVIEW

**Comment by ark3** [comment]
Thank you for the PR. Can you please explain why these changes are needed? You didn't refer to an issue in the tracker, and I don't immediately see what you're accomplishing, so some context would be helpful. Thanks!

**Comment by netag** [comment]
@ark3 thanks for the prompt response. 

Since in our Kubernetes cluster we use an annotation which injects a wrapper for the command to allow access to secrets (like vault). The tool that does the injection needs the command to be part of the deployment (this way it knows how to "replace" the original command with a command that is wrapped by the tool).

In telepresense we get another wrapper, but since this wrapper command is not explicitly part of the deployment, our wrapper misses it and runs the command from the telepresense deployment, which is an empty string.

This pr helps us support our use case with full backward compatibility for the current version.

**Comment by vladshub** [comment]
Any movement on this?

**Comment by netag** [comment]
hi @ark3, do you have any update around this?

**Comment by vladshub** [comment]
Hi, any updates on this?

**Pull request merged**
