### PR TITLE
Update Telepresence to use new staging cluster

### PR DESCRIPTION
**Pull request by ghost**
## Description

A new staging cluster is available to replace the current one.
New cluster uses the hostnames staging-app.datawire.io and staging-auth.datawire.io instead of beta-app.datawire.io and beta-auth.datawire.io

This PR updates Telepresence to use the new hostnames

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [x] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

### CODE REVIEW

**Review by AidanWenzel — APPROVED** [review]

**Review by AidanWenzel — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by josecv — APPROVED** [review]
lgtm but pls rebase to keep only your commits

**Comment by ghost** [comment]
@josecv Those commits are showing because of a rebase but the only files changed are the ones I modified so nothing unexpected will be committed once I merge.

**Review by AJC87 — APPROVED** [review]
LGTM! :shipit:

**Comment by ghost** [comment]
I've updated commit history to be clean

**Review by josecv — APPROVED** [review]

**Pull request merged**
